// Central definition of network packet identifiers used by client and server code.

type PacketCodeMap = Readonly<Record<string, string>>;

const LEGACY_CLIENT_CODES = Object.freeze({
  RESPOND_ALLIANCE_REQUEST: '11',
  KICK_ALLIANCE_MEMBER: '12',
  REQUEST_ALLIANCE_JOIN: '10',
  CREATE_ALLIANCE: '8',
  LEAVE_ALLIANCE: '9',
  STORE_ACTION: '13c',
  SEND_CHAT: 'ch',
  RESET_MOVE_DIR: 'rmd',
  SET_ATTACK_STATE: 'c',
  SET_MOVE_DIR: '33',
  TOGGLE_LOCK_DIR: '7',
  AUTO_GATHER: '7',
  SEND_MAP_PING: '14',
  SELECT_TO_BUILD: '5',
  SPAWN_PLAYER: 'sp',
  PURCHASE_UPGRADE: '6',
  UPDATE_AIM_DIR: '2',
  REQUEST_PING: 'pp',
  PING: 'pp',
} as const satisfies PacketCodeMap);

const LEGACY_SERVER_CODES = Object.freeze({
  INIT_DATA: 'id',
  DISCONNECT: 'd',
  SETUP_GAME: '1',
  ADD_PLAYER: '2',
  REMOVE_PLAYER: '4',
  UPDATE_PLAYERS: '33',
  UPDATE_LEADERBOARD: '5',
  LOAD_GAME_OBJECT: '6',
  LOAD_AI: 'a',
  ANIMATE_AI: 'aa',
  GATHER_ANIMATION: '7',
  WIGGLE_GAME_OBJECT: '8',
  SHOOT_TURRET: 'sp',
  UPDATE_PLAYER_VALUE: '9',
  UPDATE_HEALTH: 'h',
  KILL_PLAYER: '11',
  KILL_OBJECT: '12',
  KILL_OBJECTS: '13',
  UPDATE_ITEM_COUNTS: '14',
  UPDATE_AGE: '15',
  UPDATE_UPGRADES: '16',
  UPDATE_ITEMS: '17',
  ADD_PROJECTILE: '18',
  REMOVE_PROJECTILE: '19',
  SERVER_SHUTDOWN_NOTICE: '20',
  ADD_ALLIANCE: 'ac',
  DELETE_ALLIANCE: 'ad',
  ALLIANCE_NOTIFICATION: 'an',
  SET_PLAYER_TEAM: 'st',
  SET_ALLIANCE_PLAYERS: 'sa',
  UPDATE_STORE_ITEMS: 'us',
  RECEIVE_CHAT: 'ch',
  UPDATE_MINIMAP: 'mm',
  SHOW_TEXT: 't',
  PING_MAP: 'p',
  PING_RESPONSE: 'pp',
} as const satisfies PacketCodeMap);

const CANONICAL_MODERN_CLIENT_CODES = Object.freeze({
  PING: '0',
  MOVE_DIRECTION: '9',
  ATTACK_BUILD_STATE: 'F',
  AIM_DIRECTION: 'D',
  ACTION_TOGGLE: 'K',
  MOVE_IMPULSE: 'S',
  RESET_KEYS: 'e',
  USE_OR_EQUIP: 'z',
  SEND_CHAT: '6',
  SPAWN_PLAYER: 'M',
  CHOOSE_UPGRADE: 'H',
  STORE_ACTION: 'c',
  RESPOND_JOIN_REQUEST: 'P',
  REQUEST_JOIN_TRIBE: 'b',
  CREATE_TRIBE: 'L',
  LEAVE_OR_DELETE_TRIBE: 'N',
} as const satisfies PacketCodeMap);

const CANONICAL_MODERN_SERVER_CODES = Object.freeze({
  INIT_TEAMS: 'A',
  DISCONNECT: 'B',
  ENTER_GAME: 'C',
  ADD_PLAYER: 'D',
  REMOVE_PLAYER: 'E',
  WORLD_SNAPSHOT: 'a',
  UPDATE_LEADERBOARD: 'G',
  UPDATE_OBJECTS: 'H',
  UPDATE_NPCS: 'I',
  START_OBJECT_ANIM: 'J',
  START_PLAYER_ANIM: 'K',
  HIT_WIGGLE: 'L',
  AIM_UPDATE: 'M',
  UPDATE_PLAYER_FIELD: 'N',
  UPDATE_HEALTH: 'O',
  KILL_PLAYER: 'P',
  KILL_OBJECT: 'Q',
  KILL_OBJECTS: 'R',
  UPDATE_ITEM_COUNTS: 'S',
  UPDATE_AGE: 'T',
  GRANT_UPGRADES: 'U',
  UPDATE_LOADOUT: 'V',
  SPAWN_PROJECTILE: 'X',
  REMOVE_PROJECTILE: 'Y',
  SERVER_SHUTDOWN_NOTICE: 'Z',
  ADD_TRIBE_ENTRY: 'g',
  REMOVE_TRIBE_ENTRY: '1',
  ADD_JOIN_REQUEST: '2',
  UPDATE_TEAM_INFO: '3',
  SET_TRIBE_MEMBERS: '4',
  UPDATE_COSMETICS: '5',
  RECEIVE_CHAT: '6',
  UPDATE_TEAM_LOCATIONS: '7',
  SHOW_TEXT: '8',
  PING_MAP: '9',
  PING_RESPONSE: '0',
} as const satisfies PacketCodeMap);

type CanonicalKey<T extends PacketCodeMap> = keyof T & string;

function buildPacketMap<TCanonical extends PacketCodeMap>(
  canonical: TCanonical,
  aliases: Record<string, CanonicalKey<TCanonical>>,
): PacketCodeMap {
  const map: Record<string, string> = { ...canonical };
  Object.entries(aliases).forEach(([alias, target]) => {
    const modernCode = canonical[target];
    if (!modernCode) {
      throw new Error(`Unknown modern packet target "${target}" for alias "${alias}"`);
    }
    map[alias] = modernCode;
  });
  return Object.freeze(map);
}

const CLIENT_PACKET_ALIASES: Record<string, CanonicalKey<typeof CANONICAL_MODERN_CLIENT_CODES>> = {
  REQUEST_PING: 'PING',
  RESPOND_ALLIANCE_REQUEST: 'RESPOND_JOIN_REQUEST',
  KICK_ALLIANCE_MEMBER: 'RESPOND_JOIN_REQUEST',
  REQUEST_ALLIANCE_JOIN: 'REQUEST_JOIN_TRIBE',
  CREATE_ALLIANCE: 'CREATE_TRIBE',
  LEAVE_ALLIANCE: 'LEAVE_OR_DELETE_TRIBE',
  SET_MOVE_DIR: 'MOVE_DIRECTION',
  RESET_MOVE_DIR: 'RESET_KEYS',
  SET_ATTACK_STATE: 'ATTACK_BUILD_STATE',
  UPDATE_AIM_DIR: 'AIM_DIRECTION',
  TOGGLE_LOCK_DIR: 'ACTION_TOGGLE',
  AUTO_GATHER: 'ACTION_TOGGLE',
  SEND_MAP_PING: 'MOVE_IMPULSE',
  SELECT_TO_BUILD: 'USE_OR_EQUIP',
  PURCHASE_UPGRADE: 'CHOOSE_UPGRADE',
};

const SERVER_PACKET_ALIASES: Record<string, CanonicalKey<typeof CANONICAL_MODERN_SERVER_CODES>> = {
  INIT_DATA: 'INIT_TEAMS',
  SETUP_GAME: 'ENTER_GAME',
  UPDATE_PLAYERS: 'WORLD_SNAPSHOT',
  LOAD_GAME_OBJECT: 'UPDATE_OBJECTS',
  LOAD_AI: 'UPDATE_NPCS',
  ANIMATE_AI: 'START_OBJECT_ANIM',
  GATHER_ANIMATION: 'START_PLAYER_ANIM',
  WIGGLE_GAME_OBJECT: 'HIT_WIGGLE',
  SHOOT_TURRET: 'AIM_UPDATE',
  UPDATE_PLAYER_VALUE: 'UPDATE_PLAYER_FIELD',
  KILL_PLAYER: 'KILL_PLAYER',
  KILL_OBJECT: 'KILL_OBJECT',
  KILL_OBJECTS: 'KILL_OBJECTS',
  UPDATE_ITEM_COUNTS: 'UPDATE_ITEM_COUNTS',
  UPDATE_AGE: 'UPDATE_AGE',
  UPDATE_UPGRADES: 'GRANT_UPGRADES',
  UPDATE_ITEMS: 'UPDATE_LOADOUT',
  ADD_PROJECTILE: 'SPAWN_PROJECTILE',
  REMOVE_PROJECTILE: 'REMOVE_PROJECTILE',
  ADD_ALLIANCE: 'ADD_TRIBE_ENTRY',
  DELETE_ALLIANCE: 'REMOVE_TRIBE_ENTRY',
  ALLIANCE_NOTIFICATION: 'ADD_JOIN_REQUEST',
  SET_PLAYER_TEAM: 'UPDATE_TEAM_INFO',
  SET_ALLIANCE_PLAYERS: 'SET_TRIBE_MEMBERS',
  UPDATE_STORE_ITEMS: 'UPDATE_COSMETICS',
  UPDATE_MINIMAP: 'UPDATE_TEAM_LOCATIONS',
};

export const MODERN_CLIENT_CODES = buildPacketMap(CANONICAL_MODERN_CLIENT_CODES, CLIENT_PACKET_ALIASES);
export const MODERN_SERVER_CODES = buildPacketMap(CANONICAL_MODERN_SERVER_CODES, SERVER_PACKET_ALIASES);

export const CLIENT_PACKETS = MODERN_CLIENT_CODES;
export const SERVER_PACKETS = MODERN_SERVER_CODES;

export const PACKETS = Object.freeze({
  CLIENT: CLIENT_PACKETS,
  SERVER: SERVER_PACKETS,
  MODERN: {
    CLIENT: CANONICAL_MODERN_CLIENT_CODES,
    SERVER: CANONICAL_MODERN_SERVER_CODES,
  },
  LEGACY: {
    CLIENT: LEGACY_CLIENT_CODES,
    SERVER: LEGACY_SERVER_CODES,
  },
});

export default PACKETS;

// CommonJS compatibility for legacy require() usage across the app.
declare const module: any;
if (typeof module !== 'undefined' && module?.exports) {
  module.exports = PACKETS;
  module.exports.CLIENT = CLIENT_PACKETS;
  module.exports.SERVER = SERVER_PACKETS;
  module.exports.MODERN = PACKETS.MODERN;
  module.exports.LEGACY = PACKETS.LEGACY;
}
