'use strict';

// AI definitions extracted from Stratums.io bundle-deobf.js
// These define the various animals/NPCs in the game

module.exports = {
  AI: [
    {
      id: 0,
      src: "cow_1",
      health: 500,
      weightM: 0.8,
      speed: 0.00095,
      turnSpeed: 0.001,
      scale: 72,
      limit: 20,
      noTrap: false,
      spawnInCave: false,
      hostile: false,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: false,
      colDmg: 0,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    },
    {
      id: 1,
      src: "pig_1",
      health: 800,
      weightM: 0.6,
      speed: 0.00085,
      turnSpeed: 0.001,
      scale: 72,
      limit: 15,
      noTrap: false,
      spawnInCave: false,
      hostile: false,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: false,
      colDmg: 0,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    },
    {
      id: 2,
      name: "Bull",
      src: "bull_2",
      dmg: 20,
      health: 1800,
      weightM: 0.5,
      speed: 0.00094,
      turnSpeed: 0.00074,
      scale: 78,
      viewRange: 800,
      chargePlayer: true,
      limit: 5,
      noTrap: false,
      spawnInCave: false,
      hostile: true,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: true,
      colDmg: 0,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    },
    {
      id: 3,
      name: "Bully",
      src: "bull_1",
      dmg: 20,
      health: 2800,
      weightM: 0.45,
      speed: 0.001,
      turnSpeed: 0.0008,
      scale: 90,
      viewRange: 900,
      chargePlayer: true,
      limit: 3,
      noTrap: false,
      spawnInCave: false,
      hostile: true,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: true,
      colDmg: 10,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    },
    {
      id: 4,
      name: "Wolf",
      src: "wolf_1",
      dmg: 8,
      health: 300,
      weightM: 0.45,
      speed: 0.001,
      turnSpeed: 0.002,
      scale: 84,
      viewRange: 800,
      chargePlayer: true,
      limit: 7,
      noTrap: false,
      spawnInCave: false,
      hostile: true,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: true,
      colDmg: 0,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    },
    {
      id: 5,
      name: "Quack",
      src: "chicken_1",
      dmg: 8,
      noTrap: true,
      health: 300,
      weightM: 0.2,
      speed: 0.0018,
      turnSpeed: 0.006,
      scale: 70,
      limit: 2,
      spawnInCave: false,
      hostile: false,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: false,
      colDmg: 0,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    },
    {
      id: 6,
      name: "MOOSTAFA",
      nameScale: 50,
      src: "enemy",
      spawnDelay: 60000,
      noTrap: true,
      dmg: 40,
      health: 18000,
      weightM: 0.4,
      speed: 0.0007,
      turnSpeed: 0.01,
      scale: 80,
      spriteMlt: 1.8,
      leapForce: 0.9,
      viewRange: 1000,
      hitRange: 210,
      chargePlayer: true,
      limit: 1,
      spawnInCave: true,
      hostile: true,
      poisonRes: true,
      nightOnly: false,
      behavior: false,
      hitDelay: 1000,
      canHit: true,
      colDmg: 100,
      hitScare: 0,
      dontRun: true,
      poisonHits: false
    },
    {
      id: 7,
      name: "Treasure",
      nameScale: 35,
      src: "crate_1",
      spawnDelay: 120000,
      health: 20000,
      weightM: 0.1,
      speed: 0,
      turnSpeed: 0,
      scale: 70,
      spriteMlt: 1,
      limit: 1,
      noTrap: false,
      spawnInCave: true,
      hostile: false,
      poisonRes: false,
      nightOnly: false,
      behavior: false,
      hitDelay: 0,
      canHit: false,
      colDmg: 200,
      hitScare: 0,
      dontRun: false,
      poisonHits: false
    }
  ]
};
